<a href="https://colab.research.google.com/github/HarisJafri-xcode/Python-for-DS/blob/main/02-NumPy/2_2_Creations_and_Universal_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating nd Array Objects

In [56]:
import numpy as np # importing the NumPy Module

In [57]:
np.zeros(10) # Creating 1D Array with 10 Elements

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [58]:
np.zeros((3,6)) # 2D NumPy Array with 3 Rows and 6 Columns with all 0 Elements

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [59]:
np.empty((2,3,2)) # Faster with Garbage Values

array([[[2.47278597e-315, 0.00000000e+000],
        [2.12199584e-314, 2.12199579e-314],
        [3.75593255e-312, 0.00000000e+000]],

       [[0.00000000e+000, 2.12199588e-314],
        [2.12199579e-314, 3.77715251e-312],
        [0.00000000e+000, 0.00000000e+000]]])

In [60]:
np.arange(15) # Based on range() Function of Python

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [61]:
np.arange(2,7) # Based on range() Function of Python

array([2, 3, 4, 5, 6])

In [62]:
np.arange(9, 18, 2) # Based on range() Function of Python

array([ 9, 11, 13, 15, 17])

# Arithmetic Operations with NumPy Arrays

In [63]:
list_1 = [1, 2, 3] # Python Built-in List
list_2 = [1, 2, 3]

In [64]:
list_1 + list_2 # Addition Operation

[1, 2, 3, 1, 2, 3]

Subtraction and other operations are not possible between Lists. Also adding a list with another list simply joins the list together.

Any arithmetic operations between equal-size arrays applies the operation element-wise also called Vectorization.

In [65]:
arr_1 = np.arange(1,4)
arr_2 = np.arange(11,14)
print(arr_1)
print(arr_2)

[1 2 3]
[11 12 13]


In [66]:
arr_1 + arr_2 # Addition Operation

array([12, 14, 16])

In [67]:
arr_1 - arr_2 # Subtraction Operation

array([-10, -10, -10])

In [68]:
arr_1 * arr_2 # Multiplication Operation

array([11, 24, 39])

In [69]:
arr_1 / arr_2 # Division Operation

array([0.09090909, 0.16666667, 0.23076923])

Arithmetic operations with scalars propagate the scalar argument to each element in the array:

In [70]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [71]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [72]:
arr / 10

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6]])

In [73]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [74]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [75]:
arr2 > arr # Element wise Operation

array([[False,  True, False],
       [ True, False,  True]])

# View vs Copy

In [76]:
arr = np.arange(10) # Creating a 1 NumPy Array

In [77]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
arr_slice = arr[1:4] # Creating a Slice that is essentially a View

In [79]:
arr_slice

array([1, 2, 3])

In [80]:
arr_slice[1] = 100 # Changing Element at Index 1 of the Slice

In [81]:
arr # Reflected in Original Array

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9])

In [82]:
arr_copy = arr[1:4].copy() # Creating a Copy of the Slice

In [83]:
arr_copy[1] = 200 # Changing an Element from the Copy

In [84]:
arr_copy

array([  1, 200,   3])

In [85]:
arr

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9])

# Boolean Indexing

In [86]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [87]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [88]:
names[names == 'Bob']

array(['Bob', 'Bob'], dtype='<U4')

In [89]:
array_1 = np.arange(0,20,2)
array_1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [90]:
array_1 > 10

array([False, False, False, False, False, False,  True,  True,  True,
        True])

We can also assigning particular values after referencing them via Boolean Values.

In [91]:
array_1[array_1 > 10] = 100

In [92]:
array_1

array([  0,   2,   4,   6,   8,  10, 100, 100, 100, 100])

# Transposing Arrays & Swapping Axis

Transposing is a special form of reshaping that similarly returns a view on the under‐lying data without copying anything. Arrays have the transpose method and also the special T attribute:


In [93]:
arr = np.arange(20).reshape(4,5)

In [94]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [95]:
arr_T = arr.T

In [96]:
arr_T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [97]:
np.dot(arr, arr_T)

array([[  30,   80,  130,  180],
       [  80,  255,  430,  605],
       [ 130,  430,  730, 1030],
       [ 180,  605, 1030, 1455]])

# Universal Functions

In [98]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
arr_2 = arr.reshape(2,5)
arr_2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [108]:
print(np.max(arr)) # Sum 1D Array

9


In [102]:
print(np.sum(arr_2, axis=0)) # Collapse the Rows

[ 5  7  9 11 13]


In [106]:
print(np.sum(arr_2, axis=1, keepdims=True)) # Collapse the Columns while keeping it 2D

[[10]
 [35]]


In [109]:
print(np.sum(arr_2)) # Sum 2D Array

45


In [112]:
print(np.min(arr_2, axis=0)) # find the minimum along each Column i.e. Collapse all rows

[0 1 2 3 4]


In [114]:
print(np.sqrt(arr_2))

[[0.         1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712 3.        ]]


# Random

In [118]:
np.random.random(size=(2,3)) # Draw from Continous Uniform Distribution of 0 and 1

array([[0.89431908, 0.71779175, 0.72005598],
       [0.9769784 , 0.74926411, 0.13269141]])

In [119]:
np.random.randint(low=3, high=10, size=(2,3)) # Draw from Discrete Uniform between 3 and 10

array([[5, 6, 8],
       [5, 3, 8]])

In [123]:
np.random.randn(2,3) # Draw from Standard Normal Mean of 0 and St.Dev 1

array([[ 0.16461037, -0.85503689, -1.23868239],
       [ 0.24430275,  0.20495004, -0.74969865]])

In [124]:
np.random.normal(loc=5, scale=2, size=(2,3)) # Draw from Normal Distribution with mean of 5 and st. dev of 2

array([[5.80061828, 5.14849025, 5.34938287],
       [2.9339484 , 6.19509337, 6.21089527]])